{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation copyModel
module Ollama.Api.Operations.CopyModel where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Ollama.Api.Common
import Ollama.Api.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | > POST /api/copy
--
-- Copy a model to a new name
copyModel ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  CopyModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response CopyModelResponse)
copyModel body =
  GHC.Internal.Base.fmap
    ( \response_0 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either CopyModelResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> GHC.Internal.Data.Either.Right CopyModelResponse200
                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                            CopyModelResponse400
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                            CopyModelResponse404
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_0
          )
          response_0
    )
    (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/copy" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | Defines the object schema located at @paths.\/api\/copy.POST.requestBody.content.application\/json.schema@ in the specification.
data CopyModelRequestBody = CopyModelRequestBody
  { -- | destination: Destination model name
    copyModelRequestBodyDestination :: Data.Text.Internal.Text,
    -- | source: Source model name
    copyModelRequestBodySource :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON CopyModelRequestBody where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (["destination" Data.Aeson.Types.ToJSON..= copyModelRequestBodyDestination obj] : ["source" Data.Aeson.Types.ToJSON..= copyModelRequestBodySource obj] : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (["destination" Data.Aeson.Types.ToJSON..= copyModelRequestBodyDestination obj] : ["source" Data.Aeson.Types.ToJSON..= copyModelRequestBodySource obj] : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON CopyModelRequestBody where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "CopyModelRequestBody" (\obj -> (GHC.Internal.Base.pure CopyModelRequestBody GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "destination")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "source"))

-- | Create a new 'CopyModelRequestBody' with all required fields.
mkCopyModelRequestBody ::
  -- | 'copyModelRequestBodyDestination'
  Data.Text.Internal.Text ->
  -- | 'copyModelRequestBodySource'
  Data.Text.Internal.Text ->
  CopyModelRequestBody
mkCopyModelRequestBody copyModelRequestBodyDestination copyModelRequestBodySource =
  CopyModelRequestBody
    { copyModelRequestBodyDestination = copyModelRequestBodyDestination,
      copyModelRequestBodySource = copyModelRequestBodySource
    }

-- | Represents a response of the operation 'copyModel'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'CopyModelResponseError' is used.
data CopyModelResponse
  = -- | Means either no matching case available or a parse error
    CopyModelResponseError GHC.Internal.Base.String
  | -- | Model copied
    CopyModelResponse200
  | -- | Bad request
    CopyModelResponse400 ErrorResponse
  | -- | Source model not found
    CopyModelResponse404 ErrorResponse
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

-- | > POST /api/copy
--
-- The same as 'copyModel' but accepts an explicit configuration.
copyModelWithConfiguration ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  CopyModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response CopyModelResponse)
copyModelWithConfiguration
  config
  body =
    GHC.Internal.Base.fmap
      ( \response_4 ->
          GHC.Internal.Base.fmap
            ( GHC.Internal.Data.Either.either CopyModelResponseError GHC.Internal.Base.id
                GHC.Internal.Base.. ( \response body ->
                                        if
                                          | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> GHC.Internal.Data.Either.Right CopyModelResponse200
                                          | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                              CopyModelResponse400
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                              CopyModelResponse404
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                    )
                  response_4
            )
            response_4
      )
      (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/copy" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/copy
--
-- The same as 'copyModel' but returns the raw 'Data.ByteString.ByteString'.
copyModelRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  CopyModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
copyModelRaw body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/copy" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/copy
--
-- The same as 'copyModel' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
copyModelWithConfigurationRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  CopyModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
copyModelWithConfigurationRaw
  config
  body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/copy" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)
