{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation generateEmbeddingLegacy
module Ollama.Api.Operations.GenerateEmbeddingLegacy where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Ollama.Api.Common
import Ollama.Api.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | > POST /api/embeddings
--
-- Generate a single embedding (legacy endpoint)
generateEmbeddingLegacy ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  GenerateEmbeddingLegacyRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response GenerateEmbeddingLegacyResponse)
generateEmbeddingLegacy body =
  GHC.Internal.Base.fmap
    ( \response_0 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either GenerateEmbeddingLegacyResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateEmbeddingLegacyResponse200
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  GenerateEmbeddingLegacyResponseBody200
                                                                            )
                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateEmbeddingLegacyResponse400
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateEmbeddingLegacyResponse404
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_0
          )
          response_0
    )
    (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embeddings" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | Defines the object schema located at @paths.\/api\/embeddings.POST.requestBody.content.application\/json.schema@ in the specification.
data GenerateEmbeddingLegacyRequestBody = GenerateEmbeddingLegacyRequestBody
  { -- | keep_alive: Duration value (e.g. \"5m\", \"1h\", or a number of seconds)
    generateEmbeddingLegacyRequestBodyKeep_alive :: (GHC.Internal.Maybe.Maybe Duration),
    -- | model
    generateEmbeddingLegacyRequestBodyModel :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | options: Model-specific options
    generateEmbeddingLegacyRequestBodyOptions :: (GHC.Internal.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | prompt: Text to embed
    generateEmbeddingLegacyRequestBodyPrompt :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GenerateEmbeddingLegacyRequestBody where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("keep_alive" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyKeep_alive obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("prompt" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyPrompt obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("keep_alive" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyKeep_alive obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("prompt" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyRequestBodyPrompt obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GenerateEmbeddingLegacyRequestBody where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GenerateEmbeddingLegacyRequestBody" (\obj -> (((GHC.Internal.Base.pure GenerateEmbeddingLegacyRequestBody GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "keep_alive")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "options")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "prompt"))

-- | Create a new 'GenerateEmbeddingLegacyRequestBody' with all required fields.
mkGenerateEmbeddingLegacyRequestBody :: GenerateEmbeddingLegacyRequestBody
mkGenerateEmbeddingLegacyRequestBody =
  GenerateEmbeddingLegacyRequestBody
    { generateEmbeddingLegacyRequestBodyKeep_alive = GHC.Internal.Maybe.Nothing,
      generateEmbeddingLegacyRequestBodyModel = GHC.Internal.Maybe.Nothing,
      generateEmbeddingLegacyRequestBodyOptions = GHC.Internal.Maybe.Nothing,
      generateEmbeddingLegacyRequestBodyPrompt = GHC.Internal.Maybe.Nothing
    }

-- | Represents a response of the operation 'generateEmbeddingLegacy'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'GenerateEmbeddingLegacyResponseError' is used.
data GenerateEmbeddingLegacyResponse
  = -- | Means either no matching case available or a parse error
    GenerateEmbeddingLegacyResponseError GHC.Internal.Base.String
  | -- | Embedding generated
    GenerateEmbeddingLegacyResponse200 GenerateEmbeddingLegacyResponseBody200
  | -- | Bad request
    GenerateEmbeddingLegacyResponse400 ErrorResponse
  | -- | Model not found
    GenerateEmbeddingLegacyResponse404 ErrorResponse
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

-- | Defines the object schema located at @paths.\/api\/embeddings.POST.responses.200.content.application\/json.schema@ in the specification.
data GenerateEmbeddingLegacyResponseBody200 = GenerateEmbeddingLegacyResponseBody200
  { -- | embedding
    generateEmbeddingLegacyResponseBody200Embedding :: (GHC.Internal.Maybe.Maybe [GHC.Types.Double])
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GenerateEmbeddingLegacyResponseBody200 where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("embedding" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyResponseBody200Embedding obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("embedding" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingLegacyResponseBody200Embedding obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GenerateEmbeddingLegacyResponseBody200 where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GenerateEmbeddingLegacyResponseBody200" (\obj -> GHC.Internal.Base.pure GenerateEmbeddingLegacyResponseBody200 GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "embedding"))

-- | Create a new 'GenerateEmbeddingLegacyResponseBody200' with all required fields.
mkGenerateEmbeddingLegacyResponseBody200 :: GenerateEmbeddingLegacyResponseBody200
mkGenerateEmbeddingLegacyResponseBody200 = GenerateEmbeddingLegacyResponseBody200 {generateEmbeddingLegacyResponseBody200Embedding = GHC.Internal.Maybe.Nothing}

-- | > POST /api/embeddings
--
-- The same as 'generateEmbeddingLegacy' but accepts an explicit configuration.
generateEmbeddingLegacyWithConfiguration ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  GenerateEmbeddingLegacyRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response GenerateEmbeddingLegacyResponse)
generateEmbeddingLegacyWithConfiguration
  config
  body =
    GHC.Internal.Base.fmap
      ( \response_4 ->
          GHC.Internal.Base.fmap
            ( GHC.Internal.Data.Either.either GenerateEmbeddingLegacyResponseError GHC.Internal.Base.id
                GHC.Internal.Base.. ( \response body ->
                                        if
                                          | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateEmbeddingLegacyResponse200
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    GenerateEmbeddingLegacyResponseBody200
                                                                              )
                                          | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateEmbeddingLegacyResponse400
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateEmbeddingLegacyResponse404
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                    )
                  response_4
            )
            response_4
      )
      (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embeddings" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/embeddings
--
-- The same as 'generateEmbeddingLegacy' but returns the raw 'Data.ByteString.ByteString'.
generateEmbeddingLegacyRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  GenerateEmbeddingLegacyRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
generateEmbeddingLegacyRaw body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embeddings" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/embeddings
--
-- The same as 'generateEmbeddingLegacy' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
generateEmbeddingLegacyWithConfigurationRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  GenerateEmbeddingLegacyRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
generateEmbeddingLegacyWithConfigurationRaw
  config
  body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embeddings" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)
