{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation generateChat
module Ollama.Api.Operations.GenerateChat where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Ollama.Api.Common
import Ollama.Api.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | > POST /api/chat
--
-- Generate the next message in a chat with a model
generateChat ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  ChatRequest ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response GenerateChatResponse)
generateChat body =
  GHC.Internal.Base.fmap
    ( \response_0 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either GenerateChatResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateChatResponse200
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ChatResponse
                                                                            )
                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateChatResponse400
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateChatResponse404
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_0
          )
          response_0
    )
    (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/chat" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | Represents a response of the operation 'generateChat'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'GenerateChatResponseError' is used.
data GenerateChatResponse
  = -- | Means either no matching case available or a parse error
    GenerateChatResponseError GHC.Internal.Base.String
  | -- | Chat response
    GenerateChatResponse200 ChatResponse
  | -- | Bad request
    GenerateChatResponse400 ErrorResponse
  | -- | Model not found
    GenerateChatResponse404 ErrorResponse
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

-- | > POST /api/chat
--
-- The same as 'generateChat' but accepts an explicit configuration.
generateChatWithConfiguration ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  ChatRequest ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response GenerateChatResponse)
generateChatWithConfiguration
  config
  body =
    GHC.Internal.Base.fmap
      ( \response_4 ->
          GHC.Internal.Base.fmap
            ( GHC.Internal.Data.Either.either GenerateChatResponseError GHC.Internal.Base.id
                GHC.Internal.Base.. ( \response body ->
                                        if
                                          | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateChatResponse200
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ChatResponse
                                                                              )
                                          | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateChatResponse400
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateChatResponse404
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                    )
                  response_4
            )
            response_4
      )
      (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/chat" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/chat
--
-- The same as 'generateChat' but returns the raw 'Data.ByteString.ByteString'.
generateChatRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  ChatRequest ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
generateChatRaw body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/chat" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/chat
--
-- The same as 'generateChat' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
generateChatWithConfigurationRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  ChatRequest ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
generateChatWithConfigurationRaw
  config
  body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/chat" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)
