{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation generateEmbedding
module Ollama.Api.Operations.GenerateEmbedding where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Ollama.Api.Common
import Ollama.Api.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | > POST /api/embed
--
-- Generate embeddings from a model
generateEmbedding ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  GenerateEmbeddingRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response GenerateEmbeddingResponse)
generateEmbedding body =
  GHC.Internal.Base.fmap
    ( \response_0 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either GenerateEmbeddingResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateEmbeddingResponse200
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  GenerateEmbeddingResponseBody200
                                                                            )
                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateEmbeddingResponse400
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GenerateEmbeddingResponse404
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_0
          )
          response_0
    )
    (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embed" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | Defines the object schema located at @paths.\/api\/embed.POST.requestBody.content.application\/json.schema@ in the specification.
data GenerateEmbeddingRequestBody = GenerateEmbeddingRequestBody
  { -- | dimensions: Truncate output embedding to this many dimensions
    generateEmbeddingRequestBodyDimensions :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | input: Text or array of text to embed
    generateEmbeddingRequestBodyInput :: (GHC.Internal.Maybe.Maybe GenerateEmbeddingRequestBodyInputVariants),
    -- | keep_alive: Duration value (e.g. \"5m\", \"1h\", or a number of seconds)
    generateEmbeddingRequestBodyKeep_alive :: (GHC.Internal.Maybe.Maybe Duration),
    -- | model
    generateEmbeddingRequestBodyModel :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | options: Model-specific options
    generateEmbeddingRequestBodyOptions :: (GHC.Internal.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | truncate: Truncate input to fit context length
    generateEmbeddingRequestBodyTruncate :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GenerateEmbeddingRequestBody where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("dimensions" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyDimensions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("input" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyInput obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("keep_alive" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyKeep_alive obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("truncate" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyTruncate obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("dimensions" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyDimensions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("input" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyInput obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("keep_alive" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyKeep_alive obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("truncate" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingRequestBodyTruncate obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GenerateEmbeddingRequestBody where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GenerateEmbeddingRequestBody" (\obj -> (((((GHC.Internal.Base.pure GenerateEmbeddingRequestBody GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "dimensions")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "input")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "keep_alive")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "options")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "truncate"))

-- | Create a new 'GenerateEmbeddingRequestBody' with all required fields.
mkGenerateEmbeddingRequestBody :: GenerateEmbeddingRequestBody
mkGenerateEmbeddingRequestBody =
  GenerateEmbeddingRequestBody
    { generateEmbeddingRequestBodyDimensions = GHC.Internal.Maybe.Nothing,
      generateEmbeddingRequestBodyInput = GHC.Internal.Maybe.Nothing,
      generateEmbeddingRequestBodyKeep_alive = GHC.Internal.Maybe.Nothing,
      generateEmbeddingRequestBodyModel = GHC.Internal.Maybe.Nothing,
      generateEmbeddingRequestBodyOptions = GHC.Internal.Maybe.Nothing,
      generateEmbeddingRequestBodyTruncate = GHC.Internal.Maybe.Nothing
    }

-- | Defines the oneOf schema located at @paths.\/api\/embed.POST.requestBody.content.application\/json.schema.properties.input.oneOf@ in the specification.
--
-- Text or array of text to embed
data GenerateEmbeddingRequestBodyInputVariants
  = GenerateEmbeddingRequestBodyInputText Data.Text.Internal.Text
  | GenerateEmbeddingRequestBodyInputListTText [Data.Text.Internal.Text]
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON GenerateEmbeddingRequestBodyInputVariants where
  toJSON (GenerateEmbeddingRequestBodyInputText a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (GenerateEmbeddingRequestBodyInputListTText a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON GenerateEmbeddingRequestBodyInputVariants where
  parseJSON val = case (GenerateEmbeddingRequestBodyInputText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((GenerateEmbeddingRequestBodyInputListTText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a
    Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a

-- | Represents a response of the operation 'generateEmbedding'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'GenerateEmbeddingResponseError' is used.
data GenerateEmbeddingResponse
  = -- | Means either no matching case available or a parse error
    GenerateEmbeddingResponseError GHC.Internal.Base.String
  | -- | Generated embeddings
    GenerateEmbeddingResponse200 GenerateEmbeddingResponseBody200
  | -- | Bad request
    GenerateEmbeddingResponse400 ErrorResponse
  | -- | Model not found
    GenerateEmbeddingResponse404 ErrorResponse
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

-- | Defines the object schema located at @paths.\/api\/embed.POST.responses.200.content.application\/json.schema@ in the specification.
data GenerateEmbeddingResponseBody200 = GenerateEmbeddingResponseBody200
  { -- | embeddings
    generateEmbeddingResponseBody200Embeddings :: (GHC.Internal.Maybe.Maybe [[GHC.Types.Float]]),
    -- | load_duration: Duration in nanoseconds
    generateEmbeddingResponseBody200Load_duration :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | model
    generateEmbeddingResponseBody200Model :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | prompt_eval_count
    generateEmbeddingResponseBody200Prompt_eval_count :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | total_duration: Duration in nanoseconds
    generateEmbeddingResponseBody200Total_duration :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GenerateEmbeddingResponseBody200 where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("embeddings" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Embeddings obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("load_duration" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Load_duration obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Model obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("prompt_eval_count" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Prompt_eval_count obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("total_duration" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Total_duration obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("embeddings" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Embeddings obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("load_duration" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Load_duration obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Model obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("prompt_eval_count" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Prompt_eval_count obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("total_duration" Data.Aeson.Types.ToJSON..=)) (generateEmbeddingResponseBody200Total_duration obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GenerateEmbeddingResponseBody200 where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GenerateEmbeddingResponseBody200" (\obj -> ((((GHC.Internal.Base.pure GenerateEmbeddingResponseBody200 GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "embeddings")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "load_duration")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "prompt_eval_count")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "total_duration"))

-- | Create a new 'GenerateEmbeddingResponseBody200' with all required fields.
mkGenerateEmbeddingResponseBody200 :: GenerateEmbeddingResponseBody200
mkGenerateEmbeddingResponseBody200 =
  GenerateEmbeddingResponseBody200
    { generateEmbeddingResponseBody200Embeddings = GHC.Internal.Maybe.Nothing,
      generateEmbeddingResponseBody200Load_duration = GHC.Internal.Maybe.Nothing,
      generateEmbeddingResponseBody200Model = GHC.Internal.Maybe.Nothing,
      generateEmbeddingResponseBody200Prompt_eval_count = GHC.Internal.Maybe.Nothing,
      generateEmbeddingResponseBody200Total_duration = GHC.Internal.Maybe.Nothing
    }

-- | > POST /api/embed
--
-- The same as 'generateEmbedding' but accepts an explicit configuration.
generateEmbeddingWithConfiguration ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  GenerateEmbeddingRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response GenerateEmbeddingResponse)
generateEmbeddingWithConfiguration
  config
  body =
    GHC.Internal.Base.fmap
      ( \response_4 ->
          GHC.Internal.Base.fmap
            ( GHC.Internal.Data.Either.either GenerateEmbeddingResponseError GHC.Internal.Base.id
                GHC.Internal.Base.. ( \response body ->
                                        if
                                          | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateEmbeddingResponse200
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    GenerateEmbeddingResponseBody200
                                                                              )
                                          | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateEmbeddingResponse400
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                              GenerateEmbeddingResponse404
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                    )
                  response_4
            )
            response_4
      )
      (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embed" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/embed
--
-- The same as 'generateEmbedding' but returns the raw 'Data.ByteString.ByteString'.
generateEmbeddingRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  GenerateEmbeddingRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
generateEmbeddingRaw body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embed" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/embed
--
-- The same as 'generateEmbedding' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
generateEmbeddingWithConfigurationRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  GenerateEmbeddingRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
generateEmbeddingWithConfigurationRaw
  config
  body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/embed" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)
