{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation getStatus
module Ollama.Api.Operations.GetStatus where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Ollama.Api.Common
import Ollama.Api.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | > GET /api/status
--
-- Get the server status including cloud information
getStatus ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response GetStatusResponse)
getStatus =
  GHC.Internal.Base.fmap
    ( \response_0 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either GetStatusResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GetStatusResponse200
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  GetStatusResponseBody200
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_0
          )
          response_0
    )
    (Ollama.Api.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/api/status" GHC.Internal.Base.mempty)

-- | Represents a response of the operation 'getStatus'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'GetStatusResponseError' is used.
data GetStatusResponse
  = -- | Means either no matching case available or a parse error
    GetStatusResponseError GHC.Internal.Base.String
  | -- | Server status
    GetStatusResponse200 GetStatusResponseBody200
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

-- | Defines the object schema located at @paths.\/api\/status.GET.responses.200.content.application\/json.schema@ in the specification.
data GetStatusResponseBody200 = GetStatusResponseBody200
  { -- | cloud
    getStatusResponseBody200Cloud :: (GHC.Internal.Maybe.Maybe GetStatusResponseBody200Cloud)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GetStatusResponseBody200 where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("cloud" Data.Aeson.Types.ToJSON..=)) (getStatusResponseBody200Cloud obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("cloud" Data.Aeson.Types.ToJSON..=)) (getStatusResponseBody200Cloud obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GetStatusResponseBody200 where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GetStatusResponseBody200" (\obj -> GHC.Internal.Base.pure GetStatusResponseBody200 GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "cloud"))

-- | Create a new 'GetStatusResponseBody200' with all required fields.
mkGetStatusResponseBody200 :: GetStatusResponseBody200
mkGetStatusResponseBody200 = GetStatusResponseBody200 {getStatusResponseBody200Cloud = GHC.Internal.Maybe.Nothing}

-- | Defines the object schema located at @paths.\/api\/status.GET.responses.200.content.application\/json.schema.properties.cloud@ in the specification.
data GetStatusResponseBody200Cloud = GetStatusResponseBody200Cloud
  { -- | disabled
    getStatusResponseBody200CloudDisabled :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool),
    -- | source
    getStatusResponseBody200CloudSource :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GetStatusResponseBody200Cloud where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("disabled" Data.Aeson.Types.ToJSON..=)) (getStatusResponseBody200CloudDisabled obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("source" Data.Aeson.Types.ToJSON..=)) (getStatusResponseBody200CloudSource obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("disabled" Data.Aeson.Types.ToJSON..=)) (getStatusResponseBody200CloudDisabled obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("source" Data.Aeson.Types.ToJSON..=)) (getStatusResponseBody200CloudSource obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GetStatusResponseBody200Cloud where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GetStatusResponseBody200Cloud" (\obj -> (GHC.Internal.Base.pure GetStatusResponseBody200Cloud GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "disabled")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "source"))

-- | Create a new 'GetStatusResponseBody200Cloud' with all required fields.
mkGetStatusResponseBody200Cloud :: GetStatusResponseBody200Cloud
mkGetStatusResponseBody200Cloud =
  GetStatusResponseBody200Cloud
    { getStatusResponseBody200CloudDisabled = GHC.Internal.Maybe.Nothing,
      getStatusResponseBody200CloudSource = GHC.Internal.Maybe.Nothing
    }

-- | > GET /api/status
--
-- The same as 'getStatus' but accepts an explicit configuration.
getStatusWithConfiguration ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response GetStatusResponse)
getStatusWithConfiguration config =
  GHC.Internal.Base.fmap
    ( \response_2 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either GetStatusResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                            GetStatusResponse200
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  GetStatusResponseBody200
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_2
          )
          response_2
    )
    (Ollama.Api.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/api/status" GHC.Internal.Base.mempty)

-- | > GET /api/status
--
-- The same as 'getStatus' but returns the raw 'Data.ByteString.ByteString'.
getStatusRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
getStatusRaw = GHC.Internal.Base.id (Ollama.Api.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/api/status" GHC.Internal.Base.mempty)

-- | > GET /api/status
--
-- The same as 'getStatus' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
getStatusWithConfigurationRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
getStatusWithConfigurationRaw config = GHC.Internal.Base.id (Ollama.Api.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "GET") "/api/status" GHC.Internal.Base.mempty)
