{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation showModel
module Ollama.Api.Operations.ShowModel where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Decoding
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Either as GHC.Internal.Data.Either
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Ollama.Api.Common
import Ollama.Api.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | > POST /api/show
--
-- Show information about a model including details, modelfile, license, etc.
showModel ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  ShowModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response ShowModelResponse)
showModel body =
  GHC.Internal.Base.fmap
    ( \response_0 ->
        GHC.Internal.Base.fmap
          ( GHC.Internal.Data.Either.either ShowModelResponseError GHC.Internal.Base.id
              GHC.Internal.Base.. ( \response body ->
                                      if
                                        | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                            ShowModelResponse200
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ShowResponse
                                                                            )
                                        | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                            ShowModelResponse400
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                            ShowModelResponse404
                                              GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                GHC.Internal.Data.Either.Either
                                                                                  GHC.Internal.Base.String
                                                                                  ErrorResponse
                                                                            )
                                        | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                  )
                response_0
          )
          response_0
    )
    (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/show" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | Defines the object schema located at @paths.\/api\/show.POST.requestBody.content.application\/json.schema@ in the specification.
data ShowModelRequestBody = ShowModelRequestBody
  { -- | model: Name of the model
    showModelRequestBodyModel :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | name: Deprecated - use model instead
    showModelRequestBodyName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | options: Additional model options
    showModelRequestBodyOptions :: (GHC.Internal.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | system: System prompt to override
    showModelRequestBodySystem :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | template: Deprecated - template override
    showModelRequestBodyTemplate :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | verbose: Show verbose output including tensor data
    showModelRequestBodyVerbose :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ShowModelRequestBody where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("system" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodySystem obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("template" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyTemplate obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("verbose" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyVerbose obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("system" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodySystem obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("template" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyTemplate obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("verbose" Data.Aeson.Types.ToJSON..=)) (showModelRequestBodyVerbose obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ShowModelRequestBody where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ShowModelRequestBody" (\obj -> (((((GHC.Internal.Base.pure ShowModelRequestBody GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "options")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "system")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "template")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "verbose"))

-- | Create a new 'ShowModelRequestBody' with all required fields.
mkShowModelRequestBody :: ShowModelRequestBody
mkShowModelRequestBody =
  ShowModelRequestBody
    { showModelRequestBodyModel = GHC.Internal.Maybe.Nothing,
      showModelRequestBodyName = GHC.Internal.Maybe.Nothing,
      showModelRequestBodyOptions = GHC.Internal.Maybe.Nothing,
      showModelRequestBodySystem = GHC.Internal.Maybe.Nothing,
      showModelRequestBodyTemplate = GHC.Internal.Maybe.Nothing,
      showModelRequestBodyVerbose = GHC.Internal.Maybe.Nothing
    }

-- | Represents a response of the operation 'showModel'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'ShowModelResponseError' is used.
data ShowModelResponse
  = -- | Means either no matching case available or a parse error
    ShowModelResponseError GHC.Internal.Base.String
  | -- | Model information
    ShowModelResponse200 ShowResponse
  | -- | Bad request
    ShowModelResponse400 ErrorResponse
  | -- | Model not found
    ShowModelResponse404 ErrorResponse
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

-- | > POST /api/show
--
-- The same as 'showModel' but accepts an explicit configuration.
showModelWithConfiguration ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  ShowModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response ShowModelResponse)
showModelWithConfiguration
  config
  body =
    GHC.Internal.Base.fmap
      ( \response_4 ->
          GHC.Internal.Base.fmap
            ( GHC.Internal.Data.Either.either ShowModelResponseError GHC.Internal.Base.id
                GHC.Internal.Base.. ( \response body ->
                                        if
                                          | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                              ShowModelResponse200
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ShowResponse
                                                                              )
                                          | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                              ShowModelResponse400
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) ->
                                              ShowModelResponse404
                                                GHC.Internal.Data.Functor.<$> ( Data.Aeson.Decoding.eitherDecodeStrict body ::
                                                                                  GHC.Internal.Data.Either.Either
                                                                                    GHC.Internal.Base.String
                                                                                    ErrorResponse
                                                                              )
                                          | GHC.Internal.Base.otherwise -> GHC.Internal.Data.Either.Left "Missing default response type"
                                    )
                  response_4
            )
            response_4
      )
      (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/show" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/show
--
-- The same as 'showModel' but returns the raw 'Data.ByteString.ByteString'.
showModelRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The request body to send
  ShowModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  Ollama.Api.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
showModelRaw body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/show" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)

-- | > POST /api/show
--
-- The same as 'showModel' but accepts an explicit configuration and returns the raw 'Data.ByteString.ByteString'.
showModelWithConfigurationRaw ::
  forall m.
  (Ollama.Api.Common.MonadHTTP m) =>
  -- | The configuration to use in the request
  Ollama.Api.Common.Configuration ->
  -- | The request body to send
  ShowModelRequestBody ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.Type.ByteString)
showModelWithConfigurationRaw
  config
  body = GHC.Internal.Base.id (Ollama.Api.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Internal.Base.$ Data.Text.Internal.pack "POST") "/api/show" GHC.Internal.Base.mempty (GHC.Internal.Maybe.Just body) Ollama.Api.Common.RequestBodyEncodingJSON)
