{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ChatRequest
module Ollama.Api.Types.ChatRequest where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import {-# SOURCE #-} Ollama.Api.Types.Duration
import {-# SOURCE #-} Ollama.Api.Types.Message
import {-# SOURCE #-} Ollama.Api.Types.ThinkValue
import {-# SOURCE #-} Ollama.Api.Types.Tool
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ChatRequest@ in the specification.
data ChatRequest = ChatRequest
  { -- | format
    chatRequestFormat :: (GHC.Internal.Maybe.Maybe ChatRequestFormatVariants),
    -- | keep_alive: Duration value (e.g. \"5m\", \"1h\", or a number of seconds)
    chatRequestKeep_alive :: (GHC.Internal.Maybe.Maybe Duration),
    -- | logprobs
    chatRequestLogprobs :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool),
    -- | messages
    chatRequestMessages :: [Message],
    -- | model
    chatRequestModel :: Data.Text.Internal.Text,
    -- | options: Model-specific options
    chatRequestOptions :: (GHC.Internal.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | shift
    chatRequestShift :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool),
    -- | stream
    chatRequestStream :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool),
    -- | think: Controls thinking\/reasoning for supported models
    chatRequestThink :: (GHC.Internal.Maybe.Maybe ThinkValue),
    -- | tools
    chatRequestTools :: (GHC.Internal.Maybe.Maybe [Tool]),
    -- | top_logprobs: Number of most likely tokens to return logprobs for (0-20)
    --
    -- Constraints:
    --
    -- * Maxium  of 20.0
    -- * Minimum  of 0.0
    chatRequestTop_logprobs :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | truncate
    chatRequestTruncate :: (GHC.Internal.Maybe.Maybe GHC.Types.Bool)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ChatRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("format" Data.Aeson.Types.ToJSON..=)) (chatRequestFormat obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("keep_alive" Data.Aeson.Types.ToJSON..=)) (chatRequestKeep_alive obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("logprobs" Data.Aeson.Types.ToJSON..=)) (chatRequestLogprobs obj) : ["messages" Data.Aeson.Types.ToJSON..= chatRequestMessages obj] : ["model" Data.Aeson.Types.ToJSON..= chatRequestModel obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (chatRequestOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("shift" Data.Aeson.Types.ToJSON..=)) (chatRequestShift obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("stream" Data.Aeson.Types.ToJSON..=)) (chatRequestStream obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("think" Data.Aeson.Types.ToJSON..=)) (chatRequestThink obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tools" Data.Aeson.Types.ToJSON..=)) (chatRequestTools obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("top_logprobs" Data.Aeson.Types.ToJSON..=)) (chatRequestTop_logprobs obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("truncate" Data.Aeson.Types.ToJSON..=)) (chatRequestTruncate obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("format" Data.Aeson.Types.ToJSON..=)) (chatRequestFormat obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("keep_alive" Data.Aeson.Types.ToJSON..=)) (chatRequestKeep_alive obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("logprobs" Data.Aeson.Types.ToJSON..=)) (chatRequestLogprobs obj) : ["messages" Data.Aeson.Types.ToJSON..= chatRequestMessages obj] : ["model" Data.Aeson.Types.ToJSON..= chatRequestModel obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("options" Data.Aeson.Types.ToJSON..=)) (chatRequestOptions obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("shift" Data.Aeson.Types.ToJSON..=)) (chatRequestShift obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("stream" Data.Aeson.Types.ToJSON..=)) (chatRequestStream obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("think" Data.Aeson.Types.ToJSON..=)) (chatRequestThink obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tools" Data.Aeson.Types.ToJSON..=)) (chatRequestTools obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("top_logprobs" Data.Aeson.Types.ToJSON..=)) (chatRequestTop_logprobs obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("truncate" Data.Aeson.Types.ToJSON..=)) (chatRequestTruncate obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ChatRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ChatRequest" (\obj -> (((((((((((GHC.Internal.Base.pure ChatRequest GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "format")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "keep_alive")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "logprobs")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "messages")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "options")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "shift")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "stream")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "think")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tools")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "top_logprobs")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "truncate"))

-- | Create a new 'ChatRequest' with all required fields.
mkChatRequest ::
  -- | 'chatRequestMessages'
  [Message] ->
  -- | 'chatRequestModel'
  Data.Text.Internal.Text ->
  ChatRequest
mkChatRequest chatRequestMessages chatRequestModel =
  ChatRequest
    { chatRequestFormat = GHC.Internal.Maybe.Nothing,
      chatRequestKeep_alive = GHC.Internal.Maybe.Nothing,
      chatRequestLogprobs = GHC.Internal.Maybe.Nothing,
      chatRequestMessages = chatRequestMessages,
      chatRequestModel = chatRequestModel,
      chatRequestOptions = GHC.Internal.Maybe.Nothing,
      chatRequestShift = GHC.Internal.Maybe.Nothing,
      chatRequestStream = GHC.Internal.Maybe.Nothing,
      chatRequestThink = GHC.Internal.Maybe.Nothing,
      chatRequestTools = GHC.Internal.Maybe.Nothing,
      chatRequestTop_logprobs = GHC.Internal.Maybe.Nothing,
      chatRequestTruncate = GHC.Internal.Maybe.Nothing
    }

-- | Defines the oneOf schema located at @components.schemas.ChatRequest.properties.format.oneOf@ in the specification.
data ChatRequestFormatVariants
  = ChatRequestFormatText Data.Text.Internal.Text
  | ChatRequestFormatObject Data.Aeson.Types.Internal.Object
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON ChatRequestFormatVariants where
  toJSON (ChatRequestFormatText a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ChatRequestFormatObject a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON ChatRequestFormatVariants where
  parseJSON val = case (ChatRequestFormatText GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((ChatRequestFormatObject GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a
    Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a
