{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ErrorResponse
module Ollama.Api.Types.ErrorResponse where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ErrorResponse@ in the specification.
data ErrorResponse = ErrorResponse
  { -- | error
    errorResponseError :: Data.Text.Internal.Text,
    -- | signin_url: URL for user to sign in when unauthorized
    errorResponseSignin_url :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ErrorResponse where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (["error" Data.Aeson.Types.ToJSON..= errorResponseError obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("signin_url" Data.Aeson.Types.ToJSON..=)) (errorResponseSignin_url obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (["error" Data.Aeson.Types.ToJSON..= errorResponseError obj] : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("signin_url" Data.Aeson.Types.ToJSON..=)) (errorResponseSignin_url obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ErrorResponse where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ErrorResponse" (\obj -> (GHC.Internal.Base.pure ErrorResponse GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..: "error")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "signin_url"))

-- | Create a new 'ErrorResponse' with all required fields.
mkErrorResponse ::
  -- | 'errorResponseError'
  Data.Text.Internal.Text ->
  ErrorResponse
mkErrorResponse errorResponseError =
  ErrorResponse
    { errorResponseError = errorResponseError,
      errorResponseSignin_url = GHC.Internal.Maybe.Nothing
    }
