{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ListModelResponse
module Ollama.Api.Types.ListModelResponse where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import {-# SOURCE #-} Ollama.Api.Types.ModelDetails
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ListModelResponse@ in the specification.
data ListModelResponse = ListModelResponse
  { -- | details
    listModelResponseDetails :: (GHC.Internal.Maybe.Maybe ModelDetails),
    -- | digest
    listModelResponseDigest :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | model
    listModelResponseModel :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | modified_at
    listModelResponseModified_at :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | name
    listModelResponseName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | remote_host
    listModelResponseRemote_host :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | remote_model
    listModelResponseRemote_model :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | size
    listModelResponseSize :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ListModelResponse where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("details" Data.Aeson.Types.ToJSON..=)) (listModelResponseDetails obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("digest" Data.Aeson.Types.ToJSON..=)) (listModelResponseDigest obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (listModelResponseModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("modified_at" Data.Aeson.Types.ToJSON..=)) (listModelResponseModified_at obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (listModelResponseName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("remote_host" Data.Aeson.Types.ToJSON..=)) (listModelResponseRemote_host obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("remote_model" Data.Aeson.Types.ToJSON..=)) (listModelResponseRemote_model obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("size" Data.Aeson.Types.ToJSON..=)) (listModelResponseSize obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("details" Data.Aeson.Types.ToJSON..=)) (listModelResponseDetails obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("digest" Data.Aeson.Types.ToJSON..=)) (listModelResponseDigest obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (listModelResponseModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("modified_at" Data.Aeson.Types.ToJSON..=)) (listModelResponseModified_at obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (listModelResponseName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("remote_host" Data.Aeson.Types.ToJSON..=)) (listModelResponseRemote_host obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("remote_model" Data.Aeson.Types.ToJSON..=)) (listModelResponseRemote_model obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("size" Data.Aeson.Types.ToJSON..=)) (listModelResponseSize obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ListModelResponse where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ListModelResponse" (\obj -> (((((((GHC.Internal.Base.pure ListModelResponse GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "details")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "digest")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "modified_at")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remote_host")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "remote_model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "size"))

-- | Create a new 'ListModelResponse' with all required fields.
mkListModelResponse :: ListModelResponse
mkListModelResponse =
  ListModelResponse
    { listModelResponseDetails = GHC.Internal.Maybe.Nothing,
      listModelResponseDigest = GHC.Internal.Maybe.Nothing,
      listModelResponseModel = GHC.Internal.Maybe.Nothing,
      listModelResponseModified_at = GHC.Internal.Maybe.Nothing,
      listModelResponseName = GHC.Internal.Maybe.Nothing,
      listModelResponseRemote_host = GHC.Internal.Maybe.Nothing,
      listModelResponseRemote_model = GHC.Internal.Maybe.Nothing,
      listModelResponseSize = GHC.Internal.Maybe.Nothing
    }
