{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema Logprob
module Ollama.Api.Types.Logprob where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.Logprob@ in the specification.
data Logprob = Logprob
  { -- | bytes
    logprobBytes :: (GHC.Internal.Maybe.Maybe [GHC.Types.Int]),
    -- | logprob
    logprobLogprob :: (GHC.Internal.Maybe.Maybe GHC.Types.Double),
    -- | token
    logprobToken :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | top_logprobs
    logprobTop_logprobs :: (GHC.Internal.Maybe.Maybe [LogprobTop_logprobs])
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON Logprob where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("bytes" Data.Aeson.Types.ToJSON..=)) (logprobBytes obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("logprob" Data.Aeson.Types.ToJSON..=)) (logprobLogprob obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("token" Data.Aeson.Types.ToJSON..=)) (logprobToken obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("top_logprobs" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobs obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("bytes" Data.Aeson.Types.ToJSON..=)) (logprobBytes obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("logprob" Data.Aeson.Types.ToJSON..=)) (logprobLogprob obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("token" Data.Aeson.Types.ToJSON..=)) (logprobToken obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("top_logprobs" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobs obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON Logprob where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "Logprob" (\obj -> (((GHC.Internal.Base.pure Logprob GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "bytes")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "logprob")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "token")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "top_logprobs"))

-- | Create a new 'Logprob' with all required fields.
mkLogprob :: Logprob
mkLogprob =
  Logprob
    { logprobBytes = GHC.Internal.Maybe.Nothing,
      logprobLogprob = GHC.Internal.Maybe.Nothing,
      logprobToken = GHC.Internal.Maybe.Nothing,
      logprobTop_logprobs = GHC.Internal.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.Logprob.properties.top_logprobs.items@ in the specification.
data LogprobTop_logprobs = LogprobTop_logprobs
  { -- | bytes
    logprobTop_logprobsBytes :: (GHC.Internal.Maybe.Maybe [GHC.Types.Int]),
    -- | logprob
    logprobTop_logprobsLogprob :: (GHC.Internal.Maybe.Maybe GHC.Types.Double),
    -- | token
    logprobTop_logprobsToken :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON LogprobTop_logprobs where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("bytes" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobsBytes obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("logprob" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobsLogprob obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("token" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobsToken obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("bytes" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobsBytes obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("logprob" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobsLogprob obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("token" Data.Aeson.Types.ToJSON..=)) (logprobTop_logprobsToken obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON LogprobTop_logprobs where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "LogprobTop_logprobs" (\obj -> ((GHC.Internal.Base.pure LogprobTop_logprobs GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "bytes")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "logprob")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "token"))

-- | Create a new 'LogprobTop_logprobs' with all required fields.
mkLogprobTop_logprobs :: LogprobTop_logprobs
mkLogprobTop_logprobs =
  LogprobTop_logprobs
    { logprobTop_logprobsBytes = GHC.Internal.Maybe.Nothing,
      logprobTop_logprobsLogprob = GHC.Internal.Maybe.Nothing,
      logprobTop_logprobsToken = GHC.Internal.Maybe.Nothing
    }
