{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema Message
module Ollama.Api.Types.Message where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import {-# SOURCE #-} Ollama.Api.Types.ToolCall
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.Message@ in the specification.
data Message = Message
  { -- | content
    messageContent :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | images: Base64-encoded images
    messageImages :: (GHC.Internal.Maybe.Maybe [Data.Text.Internal.Text]),
    -- | role
    messageRole :: (GHC.Internal.Maybe.Maybe MessageRole),
    -- | thinking: Thinking\/reasoning content from the model
    messageThinking :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | tool_call_id
    messageTool_call_id :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | tool_calls
    messageTool_calls :: (GHC.Internal.Maybe.Maybe [ToolCall]),
    -- | tool_name
    messageTool_name :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON Message where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("content" Data.Aeson.Types.ToJSON..=)) (messageContent obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("images" Data.Aeson.Types.ToJSON..=)) (messageImages obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("role" Data.Aeson.Types.ToJSON..=)) (messageRole obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("thinking" Data.Aeson.Types.ToJSON..=)) (messageThinking obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tool_call_id" Data.Aeson.Types.ToJSON..=)) (messageTool_call_id obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tool_calls" Data.Aeson.Types.ToJSON..=)) (messageTool_calls obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tool_name" Data.Aeson.Types.ToJSON..=)) (messageTool_name obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("content" Data.Aeson.Types.ToJSON..=)) (messageContent obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("images" Data.Aeson.Types.ToJSON..=)) (messageImages obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("role" Data.Aeson.Types.ToJSON..=)) (messageRole obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("thinking" Data.Aeson.Types.ToJSON..=)) (messageThinking obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tool_call_id" Data.Aeson.Types.ToJSON..=)) (messageTool_call_id obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tool_calls" Data.Aeson.Types.ToJSON..=)) (messageTool_calls obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("tool_name" Data.Aeson.Types.ToJSON..=)) (messageTool_name obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON Message where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "Message" (\obj -> ((((((GHC.Internal.Base.pure Message GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "content")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "images")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "role")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "thinking")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tool_call_id")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tool_calls")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tool_name"))

-- | Create a new 'Message' with all required fields.
mkMessage :: Message
mkMessage =
  Message
    { messageContent = GHC.Internal.Maybe.Nothing,
      messageImages = GHC.Internal.Maybe.Nothing,
      messageRole = GHC.Internal.Maybe.Nothing,
      messageThinking = GHC.Internal.Maybe.Nothing,
      messageTool_call_id = GHC.Internal.Maybe.Nothing,
      messageTool_calls = GHC.Internal.Maybe.Nothing,
      messageTool_name = GHC.Internal.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.Message.properties.role@ in the specification.
data MessageRole
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    MessageRoleOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    MessageRoleTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"system"@
    MessageRoleEnumSystem
  | -- | Represents the JSON value @"user"@
    MessageRoleEnumUser
  | -- | Represents the JSON value @"assistant"@
    MessageRoleEnumAssistant
  | -- | Represents the JSON value @"tool"@
    MessageRoleEnumTool
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON MessageRole where
  toJSON (MessageRoleOther val) = val
  toJSON (MessageRoleTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (MessageRoleEnumSystem) = "system"
  toJSON (MessageRoleEnumUser) = "user"
  toJSON (MessageRoleEnumAssistant) = "assistant"
  toJSON (MessageRoleEnumTool) = "tool"

instance Data.Aeson.Types.FromJSON.FromJSON MessageRole where
  parseJSON val =
    GHC.Internal.Base.pure
      ( if
          | val GHC.Classes.== "system" -> MessageRoleEnumSystem
          | val GHC.Classes.== "user" -> MessageRoleEnumUser
          | val GHC.Classes.== "assistant" -> MessageRoleEnumAssistant
          | val GHC.Classes.== "tool" -> MessageRoleEnumTool
          | GHC.Internal.Base.otherwise -> MessageRoleOther val
      )
