{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ModelDetails
module Ollama.Api.Types.ModelDetails where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ModelDetails@ in the specification.
data ModelDetails = ModelDetails
  { -- | families
    modelDetailsFamilies :: (GHC.Internal.Maybe.Maybe [Data.Text.Internal.Text]),
    -- | family
    modelDetailsFamily :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | format
    modelDetailsFormat :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | parameter_size
    modelDetailsParameter_size :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | parent_model
    modelDetailsParent_model :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | quantization_level
    modelDetailsQuantization_level :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ModelDetails where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("families" Data.Aeson.Types.ToJSON..=)) (modelDetailsFamilies obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("family" Data.Aeson.Types.ToJSON..=)) (modelDetailsFamily obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("format" Data.Aeson.Types.ToJSON..=)) (modelDetailsFormat obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("parameter_size" Data.Aeson.Types.ToJSON..=)) (modelDetailsParameter_size obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("parent_model" Data.Aeson.Types.ToJSON..=)) (modelDetailsParent_model obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("quantization_level" Data.Aeson.Types.ToJSON..=)) (modelDetailsQuantization_level obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("families" Data.Aeson.Types.ToJSON..=)) (modelDetailsFamilies obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("family" Data.Aeson.Types.ToJSON..=)) (modelDetailsFamily obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("format" Data.Aeson.Types.ToJSON..=)) (modelDetailsFormat obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("parameter_size" Data.Aeson.Types.ToJSON..=)) (modelDetailsParameter_size obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("parent_model" Data.Aeson.Types.ToJSON..=)) (modelDetailsParent_model obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("quantization_level" Data.Aeson.Types.ToJSON..=)) (modelDetailsQuantization_level obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ModelDetails where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ModelDetails" (\obj -> (((((GHC.Internal.Base.pure ModelDetails GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "families")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "family")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "format")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "parameter_size")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "parent_model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "quantization_level"))

-- | Create a new 'ModelDetails' with all required fields.
mkModelDetails :: ModelDetails
mkModelDetails =
  ModelDetails
    { modelDetailsFamilies = GHC.Internal.Maybe.Nothing,
      modelDetailsFamily = GHC.Internal.Maybe.Nothing,
      modelDetailsFormat = GHC.Internal.Maybe.Nothing,
      modelDetailsParameter_size = GHC.Internal.Maybe.Nothing,
      modelDetailsParent_model = GHC.Internal.Maybe.Nothing,
      modelDetailsQuantization_level = GHC.Internal.Maybe.Nothing
    }
