{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ModelRecommendation
module Ollama.Api.Types.ModelRecommendation where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ModelRecommendation@ in the specification.
data ModelRecommendation = ModelRecommendation
  { -- | context_length
    modelRecommendationContext_length :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | description
    modelRecommendationDescription :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | max_output_tokens
    modelRecommendationMax_output_tokens :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | model
    modelRecommendationModel :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | required_plan
    modelRecommendationRequired_plan :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | vram_bytes
    modelRecommendationVram_bytes :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ModelRecommendation where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("context_length" Data.Aeson.Types.ToJSON..=)) (modelRecommendationContext_length obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (modelRecommendationDescription obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("max_output_tokens" Data.Aeson.Types.ToJSON..=)) (modelRecommendationMax_output_tokens obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (modelRecommendationModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("required_plan" Data.Aeson.Types.ToJSON..=)) (modelRecommendationRequired_plan obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("vram_bytes" Data.Aeson.Types.ToJSON..=)) (modelRecommendationVram_bytes obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("context_length" Data.Aeson.Types.ToJSON..=)) (modelRecommendationContext_length obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (modelRecommendationDescription obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("max_output_tokens" Data.Aeson.Types.ToJSON..=)) (modelRecommendationMax_output_tokens obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (modelRecommendationModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("required_plan" Data.Aeson.Types.ToJSON..=)) (modelRecommendationRequired_plan obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("vram_bytes" Data.Aeson.Types.ToJSON..=)) (modelRecommendationVram_bytes obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ModelRecommendation where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ModelRecommendation" (\obj -> (((((GHC.Internal.Base.pure ModelRecommendation GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "context_length")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "max_output_tokens")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "required_plan")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "vram_bytes"))

-- | Create a new 'ModelRecommendation' with all required fields.
mkModelRecommendation :: ModelRecommendation
mkModelRecommendation =
  ModelRecommendation
    { modelRecommendationContext_length = GHC.Internal.Maybe.Nothing,
      modelRecommendationDescription = GHC.Internal.Maybe.Nothing,
      modelRecommendationMax_output_tokens = GHC.Internal.Maybe.Nothing,
      modelRecommendationModel = GHC.Internal.Maybe.Nothing,
      modelRecommendationRequired_plan = GHC.Internal.Maybe.Nothing,
      modelRecommendationVram_bytes = GHC.Internal.Maybe.Nothing
    }
