{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ProcessModelResponse
module Ollama.Api.Types.ProcessModelResponse where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import {-# SOURCE #-} Ollama.Api.Types.ModelDetails
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ProcessModelResponse@ in the specification.
data ProcessModelResponse = ProcessModelResponse
  { -- | context_length
    processModelResponseContext_length :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | details
    processModelResponseDetails :: (GHC.Internal.Maybe.Maybe ModelDetails),
    -- | digest
    processModelResponseDigest :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | expires_at
    processModelResponseExpires_at :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | model
    processModelResponseModel :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | name
    processModelResponseName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | size
    processModelResponseSize :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | size_vram
    processModelResponseSize_vram :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ProcessModelResponse where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("context_length" Data.Aeson.Types.ToJSON..=)) (processModelResponseContext_length obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("details" Data.Aeson.Types.ToJSON..=)) (processModelResponseDetails obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("digest" Data.Aeson.Types.ToJSON..=)) (processModelResponseDigest obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("expires_at" Data.Aeson.Types.ToJSON..=)) (processModelResponseExpires_at obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (processModelResponseModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (processModelResponseName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("size" Data.Aeson.Types.ToJSON..=)) (processModelResponseSize obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("size_vram" Data.Aeson.Types.ToJSON..=)) (processModelResponseSize_vram obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("context_length" Data.Aeson.Types.ToJSON..=)) (processModelResponseContext_length obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("details" Data.Aeson.Types.ToJSON..=)) (processModelResponseDetails obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("digest" Data.Aeson.Types.ToJSON..=)) (processModelResponseDigest obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("expires_at" Data.Aeson.Types.ToJSON..=)) (processModelResponseExpires_at obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (processModelResponseModel obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (processModelResponseName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("size" Data.Aeson.Types.ToJSON..=)) (processModelResponseSize obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("size_vram" Data.Aeson.Types.ToJSON..=)) (processModelResponseSize_vram obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ProcessModelResponse where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ProcessModelResponse" (\obj -> (((((((GHC.Internal.Base.pure ProcessModelResponse GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "context_length")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "details")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "digest")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "expires_at")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "size")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "size_vram"))

-- | Create a new 'ProcessModelResponse' with all required fields.
mkProcessModelResponse :: ProcessModelResponse
mkProcessModelResponse =
  ProcessModelResponse
    { processModelResponseContext_length = GHC.Internal.Maybe.Nothing,
      processModelResponseDetails = GHC.Internal.Maybe.Nothing,
      processModelResponseDigest = GHC.Internal.Maybe.Nothing,
      processModelResponseExpires_at = GHC.Internal.Maybe.Nothing,
      processModelResponseModel = GHC.Internal.Maybe.Nothing,
      processModelResponseName = GHC.Internal.Maybe.Nothing,
      processModelResponseSize = GHC.Internal.Maybe.Nothing,
      processModelResponseSize_vram = GHC.Internal.Maybe.Nothing
    }
