{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ProgressResponse
module Ollama.Api.Types.ProgressResponse where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ProgressResponse@ in the specification.
data ProgressResponse = ProgressResponse
  { -- | completed
    progressResponseCompleted :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | digest
    progressResponseDigest :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | status
    progressResponseStatus :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | total
    progressResponseTotal :: (GHC.Internal.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ProgressResponse where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("completed" Data.Aeson.Types.ToJSON..=)) (progressResponseCompleted obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("digest" Data.Aeson.Types.ToJSON..=)) (progressResponseDigest obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("status" Data.Aeson.Types.ToJSON..=)) (progressResponseStatus obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("total" Data.Aeson.Types.ToJSON..=)) (progressResponseTotal obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("completed" Data.Aeson.Types.ToJSON..=)) (progressResponseCompleted obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("digest" Data.Aeson.Types.ToJSON..=)) (progressResponseDigest obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("status" Data.Aeson.Types.ToJSON..=)) (progressResponseStatus obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("total" Data.Aeson.Types.ToJSON..=)) (progressResponseTotal obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ProgressResponse where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ProgressResponse" (\obj -> (((GHC.Internal.Base.pure ProgressResponse GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "completed")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "digest")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "status")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "total"))

-- | Create a new 'ProgressResponse' with all required fields.
mkProgressResponse :: ProgressResponse
mkProgressResponse =
  ProgressResponse
    { progressResponseCompleted = GHC.Internal.Maybe.Nothing,
      progressResponseDigest = GHC.Internal.Maybe.Nothing,
      progressResponseStatus = GHC.Internal.Maybe.Nothing,
      progressResponseTotal = GHC.Internal.Maybe.Nothing
    }
