{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ThinkValue
module Ollama.Api.Types.ThinkValue where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the enum schema located at @components.schemas.ThinkValue.oneOf@ in the specification.
data ThinkValueOneOf2
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    ThinkValueOneOf2Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    ThinkValueOneOf2Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"high"@
    ThinkValueOneOf2EnumHigh
  | -- | Represents the JSON value @"medium"@
    ThinkValueOneOf2EnumMedium
  | -- | Represents the JSON value @"low"@
    ThinkValueOneOf2EnumLow
  | -- | Represents the JSON value @"max"@
    ThinkValueOneOf2EnumMax
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON ThinkValueOneOf2 where
  toJSON (ThinkValueOneOf2Other val) = val
  toJSON (ThinkValueOneOf2Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (ThinkValueOneOf2EnumHigh) = "high"
  toJSON (ThinkValueOneOf2EnumMedium) = "medium"
  toJSON (ThinkValueOneOf2EnumLow) = "low"
  toJSON (ThinkValueOneOf2EnumMax) = "max"

instance Data.Aeson.Types.FromJSON.FromJSON ThinkValueOneOf2 where
  parseJSON val =
    GHC.Internal.Base.pure
      ( if
          | val GHC.Classes.== "high" -> ThinkValueOneOf2EnumHigh
          | val GHC.Classes.== "medium" -> ThinkValueOneOf2EnumMedium
          | val GHC.Classes.== "low" -> ThinkValueOneOf2EnumLow
          | val GHC.Classes.== "max" -> ThinkValueOneOf2EnumMax
          | GHC.Internal.Base.otherwise -> ThinkValueOneOf2Other val
      )

-- | Defines the oneOf schema located at @components.schemas.ThinkValue.oneOf@ in the specification.
--
-- Controls thinking\/reasoning for supported models
data ThinkValueVariants
  = ThinkValueBool GHC.Types.Bool
  | ThinkValueThinkValueOneOf2 ThinkValueOneOf2
  deriving (GHC.Internal.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON ThinkValueVariants where
  toJSON (ThinkValueBool a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ThinkValueThinkValueOneOf2 a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON ThinkValueVariants where
  parseJSON val = case (ThinkValueBool GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> ((ThinkValueThinkValueOneOf2 GHC.Internal.Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Internal.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Internal.Base.pure a
    Data.Aeson.Types.Internal.Error a -> GHC.Internal.Control.Monad.Fail.fail a

-- | Defines an alias for the schema located at @components.schemas.ThinkValue.oneOf@ in the specification.
--
-- Controls thinking\/reasoning for supported models
type ThinkValue = ThinkValueVariants
