{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ToolFunction
module Ollama.Api.Types.ToolFunction where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ToolFunction@ in the specification.
data ToolFunction = ToolFunction
  { -- | description
    toolFunctionDescription :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | name
    toolFunctionName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | parameters
    toolFunctionParameters :: (GHC.Internal.Maybe.Maybe ToolFunctionParameters)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ToolFunction where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (toolFunctionDescription obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (toolFunctionName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("parameters" Data.Aeson.Types.ToJSON..=)) (toolFunctionParameters obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (toolFunctionDescription obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (toolFunctionName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("parameters" Data.Aeson.Types.ToJSON..=)) (toolFunctionParameters obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ToolFunction where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ToolFunction" (\obj -> ((GHC.Internal.Base.pure ToolFunction GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "parameters"))

-- | Create a new 'ToolFunction' with all required fields.
mkToolFunction :: ToolFunction
mkToolFunction =
  ToolFunction
    { toolFunctionDescription = GHC.Internal.Maybe.Nothing,
      toolFunctionName = GHC.Internal.Maybe.Nothing,
      toolFunctionParameters = GHC.Internal.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.ToolFunction.properties.parameters@ in the specification.
data ToolFunctionParameters = ToolFunctionParameters
  { -- | properties
    toolFunctionParametersProperties :: (GHC.Internal.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | required
    toolFunctionParametersRequired :: (GHC.Internal.Maybe.Maybe [Data.Text.Internal.Text]),
    -- | type
    toolFunctionParametersType :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ToolFunctionParameters where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("properties" Data.Aeson.Types.ToJSON..=)) (toolFunctionParametersProperties obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("required" Data.Aeson.Types.ToJSON..=)) (toolFunctionParametersRequired obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (toolFunctionParametersType obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("properties" Data.Aeson.Types.ToJSON..=)) (toolFunctionParametersProperties obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("required" Data.Aeson.Types.ToJSON..=)) (toolFunctionParametersRequired obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("type" Data.Aeson.Types.ToJSON..=)) (toolFunctionParametersType obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ToolFunctionParameters where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ToolFunctionParameters" (\obj -> ((GHC.Internal.Base.pure ToolFunctionParameters GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "properties")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "required")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "type"))

-- | Create a new 'ToolFunctionParameters' with all required fields.
mkToolFunctionParameters :: ToolFunctionParameters
mkToolFunctionParameters =
  ToolFunctionParameters
    { toolFunctionParametersProperties = GHC.Internal.Maybe.Nothing,
      toolFunctionParametersRequired = GHC.Internal.Maybe.Nothing,
      toolFunctionParametersType = GHC.Internal.Maybe.Nothing
    }
