{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ToolCall
module Ollama.Api.Types.ToolCall where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.ToolCall@ in the specification.
data ToolCall = ToolCall
  { -- | function
    toolCallFunction :: (GHC.Internal.Maybe.Maybe ToolCallFunction),
    -- | id
    toolCallId :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ToolCall where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("function" Data.Aeson.Types.ToJSON..=)) (toolCallFunction obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("id" Data.Aeson.Types.ToJSON..=)) (toolCallId obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("function" Data.Aeson.Types.ToJSON..=)) (toolCallFunction obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("id" Data.Aeson.Types.ToJSON..=)) (toolCallId obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ToolCall where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ToolCall" (\obj -> (GHC.Internal.Base.pure ToolCall GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "function")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "id"))

-- | Create a new 'ToolCall' with all required fields.
mkToolCall :: ToolCall
mkToolCall =
  ToolCall
    { toolCallFunction = GHC.Internal.Maybe.Nothing,
      toolCallId = GHC.Internal.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.ToolCall.properties.function@ in the specification.
data ToolCallFunction = ToolCallFunction
  { -- | arguments
    toolCallFunctionArguments :: (GHC.Internal.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | index
    toolCallFunctionIndex :: (GHC.Internal.Maybe.Maybe GHC.Types.Int),
    -- | name
    toolCallFunctionName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ToolCallFunction where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("arguments" Data.Aeson.Types.ToJSON..=)) (toolCallFunctionArguments obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("index" Data.Aeson.Types.ToJSON..=)) (toolCallFunctionIndex obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (toolCallFunctionName obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("arguments" Data.Aeson.Types.ToJSON..=)) (toolCallFunctionArguments obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("index" Data.Aeson.Types.ToJSON..=)) (toolCallFunctionIndex obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (toolCallFunctionName obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ToolCallFunction where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ToolCallFunction" (\obj -> ((GHC.Internal.Base.pure ToolCallFunction GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "arguments")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "index")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name"))

-- | Create a new 'ToolCallFunction' with all required fields.
mkToolCallFunction :: ToolCallFunction
mkToolCallFunction =
  ToolCallFunction
    { toolCallFunctionArguments = GHC.Internal.Maybe.Nothing,
      toolCallFunctionIndex = GHC.Internal.Maybe.Nothing,
      toolCallFunctionName = GHC.Internal.Maybe.Nothing
    }
