{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema UserResponse
module Ollama.Api.Types.UserResponse where

import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Ollama.Api.Common
import Ollama.Api.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Internal.Maybe
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.UserResponse@ in the specification.
data UserResponse = UserResponse
  { -- | avatarurl
    userResponseAvatarurl :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | bio
    userResponseBio :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | email
    userResponseEmail :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | firstname
    userResponseFirstname :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | id
    userResponseId :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | lastname
    userResponseLastname :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | name
    userResponseName :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text),
    -- | plan
    userResponsePlan :: (GHC.Internal.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Internal.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON UserResponse where
  toJSON obj = Data.Aeson.Types.Internal.object (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("avatarurl" Data.Aeson.Types.ToJSON..=)) (userResponseAvatarurl obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("bio" Data.Aeson.Types.ToJSON..=)) (userResponseBio obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (userResponseEmail obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("firstname" Data.Aeson.Types.ToJSON..=)) (userResponseFirstname obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("id" Data.Aeson.Types.ToJSON..=)) (userResponseId obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("lastname" Data.Aeson.Types.ToJSON..=)) (userResponseLastname obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (userResponseName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("plan" Data.Aeson.Types.ToJSON..=)) (userResponsePlan obj) : GHC.Internal.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Internal.Base.mconcat (GHC.Internal.Data.Foldable.concat (GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("avatarurl" Data.Aeson.Types.ToJSON..=)) (userResponseAvatarurl obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("bio" Data.Aeson.Types.ToJSON..=)) (userResponseBio obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (userResponseEmail obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("firstname" Data.Aeson.Types.ToJSON..=)) (userResponseFirstname obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("id" Data.Aeson.Types.ToJSON..=)) (userResponseId obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("lastname" Data.Aeson.Types.ToJSON..=)) (userResponseLastname obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (userResponseName obj) : GHC.Internal.Data.Maybe.maybe GHC.Internal.Base.mempty (GHC.Internal.Base.pure GHC.Internal.Base.. ("plan" Data.Aeson.Types.ToJSON..=)) (userResponsePlan obj) : GHC.Internal.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON UserResponse where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "UserResponse" (\obj -> (((((((GHC.Internal.Base.pure UserResponse GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "avatarurl")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "bio")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "email")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "firstname")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "id")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "lastname")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Internal.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "plan"))

-- | Create a new 'UserResponse' with all required fields.
mkUserResponse :: UserResponse
mkUserResponse =
  UserResponse
    { userResponseAvatarurl = GHC.Internal.Maybe.Nothing,
      userResponseBio = GHC.Internal.Maybe.Nothing,
      userResponseEmail = GHC.Internal.Maybe.Nothing,
      userResponseFirstname = GHC.Internal.Maybe.Nothing,
      userResponseId = GHC.Internal.Maybe.Nothing,
      userResponseLastname = GHC.Internal.Maybe.Nothing,
      userResponseName = GHC.Internal.Maybe.Nothing,
      userResponsePlan = GHC.Internal.Maybe.Nothing
    }
