-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the default configuration
module Ollama.Api.Configuration where

import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified GHC.Types
import qualified Ollama.Api.Common

-- | The default url specified by the OpenAPI specification
--
-- @http://localhost:11434@
defaultURL = Data.Text.Internal.pack "http://localhost:11434"

-- | The default application name used in the @User-Agent@ header which is based on the @info.title@ field of the specification
--
-- @Ollama API@
defaultApplicationName = Data.Text.Internal.pack "Ollama API"

-- | The default configuration containing the 'defaultURL' and no authorization
defaultConfiguration = Ollama.Api.Common.Configuration defaultURL Ollama.Api.Common.anonymousSecurityScheme GHC.Types.True defaultApplicationName
